<a href="https://colab.research.google.com/github/wanchart/Study-Pytorch/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np

# List



In [2]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


# Numpy Arrays

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.63130606, 0.43430219, 0.68883389, 0.61969323],
       [0.09375682, 0.12471351, 0.72000815, 0.42885376],
       [0.92813163, 0.81056113, 0.98271332, 0.61092262]])

# Tensors

In [7]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.6685, 0.3946, 0.6555, 0.8163],
        [0.2185, 0.0053, 0.5886, 0.0564],
        [0.9222, 0.5626, 0.5864, 0.7702]])

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6313, 0.4343, 0.6888, 0.6197],
        [0.0938, 0.1247, 0.7200, 0.4289],
        [0.9281, 0.8106, 0.9827, 0.6109]], dtype=torch.float64)